apiVersion: v1
kind: ConfigMap
metadata:
  name: appinsights-config
  namespace: appinsightdemo
data:
  JAVA_OPTS: "-Xms256m -Xmx512m"
  APP_NAME: "azure-appinsights-java-demo"
  SPRING_PROFILES_ACTIVE: "production"
---
apiVersion: v1
kind: Secret
metadata:
  name: appinsights-secret
  namespace: appinsightdemo
type: Opaque
stringData:
  APPLICATIONINSIGHTS_CONNECTION_STRING: ""