apiVersion: v1
kind: Namespace
metadata:
  name: appinsightdemo
  labels:
    name: appinsightdemo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-appinsights-java-demo
  namespace: appinsightdemo
  labels:
    app: azure-appinsights-java-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: azure-appinsights-java-demo
  template:
    metadata:
      labels:
        app: azure-appinsights-java-demo
    spec:
      containers:
      - name: azure-appinsights-java-demo
        image: khanasif1/azure-appinsights-java-demo:latest
        ports:
        - containerPort: 8082
          name: http
        env:
        - name: APPLICATIONINSIGHTS_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: appinsights-secret
              key: APPLICATIONINSIGHTS_CONNECTION_STRING
        - name: JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: appinsights-config
              key: JAVA_OPTS
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: appinsights-config
              key: APP_NAME
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: appinsights-config
              key: SPRING_PROFILES_ACTIVE
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8082
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: azure-appinsights-java-demo-service
  namespace: appinsightdemo
  labels:
    app: azure-appinsights-java-demo
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8082
    protocol: TCP
    name: http
  selector:
    app: azure-appinsights-java-demo